name: CI

on: pull_request

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: github action checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: use Node 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install packages
              run: yarn install --immutable

            - name: Build packages
              run: yarn build

            - name: Publish to Chromatic
              uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  buildScriptName: build:storybook
